---
git:
  depth: 1
language: node_js
node_js:
  - lts/*
  - stable
cache: npm
notification:
  email: false
script:
  - npm run lint -- --max-warnings=0 || travis_terminate 1
  - npm run flow || travis_terminate 1
  - npm run test || travis_terminate 1
