environment:
  matrix:
    - node_version: "lts"
    - node_version: "stable"

matrix:
  fast_finish: true

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:node_version x64
  - set CI=true
  - npm install

test_script:
  - npm run lint -- --max-warnings=0
  - npm run flow
  - npm run test

cache: npm

# Don't actually build.
build: off
